### ISSUE TITLE
WADA SNR integral computation

### ISSUE THREAD

**Issue by nervjack2** [ludlows/snreval#3]
Hi,

Are you be able to share to code for computing the integral in WADA SNR?
I have to tune the parameter alpha on my dataset.
https://github.com/ludlows/snreval/blob/master/wada_snr.m#L21
It is quite hard for us to implement one, thanks!

**Comment by Kit-Bower-Morris** [comment]
@nervjack2 Did you manage to compute the 0.5 alpha curve in the end? I can't find it anywhere and that maths is far beyond me!

**Comment by nervjack2** [comment]
I remember that you can find it on the official website of the paper author.
